#!/usr/bin/env python3
"""
visualize_weather_rasters.py
============================

Purpose
-------
Create a ready-to-share three-panel visualization from the weather rasters
 generated by `download_weather_rasters.py`.

What it shows
-------------
- left: temperature_2m
- middle: relative_humidity_2m
- right: wind_speed_10m

Optional background
-------------------
You can pass a georeferenced raster, for example a satellite TIFF aligned to
the same grid. The weather layer is then shown on top of that background.

Example
-------
python weather_raster_solution/visualize_weather_rasters.py \
  --input-dir weather_raster_solution/output \
  --timestamp 2024-07-04T12:00 \
  --background-raster krakow_background_B04.tif \
  --output weather_raster_solution/weather_overview.png
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import rasterio
from rasterio.warp import Resampling, reproject


DEFAULT_VARIABLES = [
    ("temperature_2m", "Temperature", "inferno"),
    ("relative_humidity_2m", "Relative Humidity", "Blues"),
    ("wind_speed_10m", "Wind Speed", "viridis"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a three-panel weather raster visualization."
    )
    parser.add_argument(
        "--input-dir",
        default="weather_raster_solution/output",
        help="Directory containing weather GeoTIFF rasters",
    )
    parser.add_argument(
        "--timestamp",
        default=None,
        help="Timestamp to render, e.g. 2024-07-04T12:00. Defaults to the first band.",
    )
    parser.add_argument(
        "--background-raster",
        default=None,
        help="Optional georeferenced background raster",
    )
    parser.add_argument(
        "--output",
        default="weather_raster_solution/weather_overview.png",
        help="Output PNG path",
    )
    return parser.parse_args()


def find_band_index(src: rasterio.io.DatasetReader, timestamp: str | None) -> int:
    if timestamp is None:
        return 1

    normalized = timestamp.strip().replace("Z", "")
    descriptions = list(src.descriptions)
    if normalized not in descriptions:
        raise SystemExit(f"Timestamp '{normalized}' not found in {src.name}")
    return descriptions.index(normalized) + 1


def load_background(
    background_path: str,
    reference: rasterio.io.DatasetReader,
) -> np.ndarray:
    background = np.full((reference.height, reference.width), np.nan, dtype=np.float32)
    with rasterio.open(background_path) as src:
        reproject(
            source=rasterio.band(src, 1),
            destination=background,
            src_transform=src.transform,
            src_crs=src.crs,
            dst_transform=reference.transform,
            dst_crs=reference.crs,
            resampling=Resampling.bilinear,
            src_nodata=src.nodata,
            dst_nodata=np.nan,
        )
    return background


def main() -> int:
    args = parse_args()
    input_dir = Path(args.input_dir)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    raster_paths = [input_dir / f"{variable}.tif" for variable, _, _ in DEFAULT_VARIABLES]
    for path in raster_paths:
        if not path.exists():
            raise SystemExit(f"Missing raster: {path}")

    with rasterio.open(raster_paths[0]) as reference:
        band_index = find_band_index(reference, args.timestamp)
        extent = [
            reference.bounds.left,
            reference.bounds.right,
            reference.bounds.bottom,
            reference.bounds.top,
        ]
        resolved_timestamp = reference.descriptions[band_index - 1]
        background = (
            load_background(args.background_raster, reference)
            if args.background_raster
            else None
        )

    fig, axes = plt.subplots(1, 3, figsize=(18, 6), constrained_layout=True)

    for ax, (variable, title, cmap), path in zip(axes, DEFAULT_VARIABLES, raster_paths):
        with rasterio.open(path) as src:
            data = src.read(band_index)
            unit = src.tags().get("unit", "")

        if background is not None:
            ax.imshow(background, extent=extent, origin="upper", cmap="gray")
            alpha = 0.68
        else:
            alpha = 0.9

        image = ax.imshow(
            data,
            extent=extent,
            origin="upper",
            cmap=cmap,
            alpha=alpha,
        )
        ax.set_title(f"{title}\n{resolved_timestamp} UTC")
        ax.set_xlabel("UTM X")
        ax.set_ylabel("UTM Y")
        cbar = fig.colorbar(image, ax=ax, fraction=0.046, pad=0.04)
        cbar.set_label(unit or variable)

    plt.savefig(output_path, dpi=180)
    plt.close(fig)
    print(f"Saved {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
